const LABEL_NODETYPE_BRANCH = `Container`;
const LABEL_NODETYPE_LEAF = `Offset`;
const LABEL_ENABLED = `Enabled`;
const LABEL_DISABLED = `Disabled`
export {LABEL_NODETYPE_BRANCH, LABEL_NODETYPE_LEAF, LABEL_ENABLED, LABEL_DISABLED};